# PANDAS LIBRARY

#### 1) Reading the CSV file

In [3]:
import pandas as pd
var=pd.read_csv("E:\ARTIFICIAL INTELLIGENCE\PANDAS\FILES\hw_200.csv")
var

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

#### 2)Reading excel file

In [1]:
import pandas as pd
excel=pd.read_excel("E:\ARTIFICIAL INTELLIGENCE\PANDAS\FILES\Sname.xlsx")
excel

   SR NO      NAME
0      1      Aman
1      2    Manish
2      3     Suraj
3      4    Amresh
4      5   Jagdish
5      6  Mahendra
6      7    Vishal
7      8    Saleem
8      9     Sunny
9     10     Sumer

#### 3) reading json file

In [2]:
sql=pd.read_json("E:\ARTIFICIAL INTELLIGENCE\PANDAS\FILES\myJason.json")
sql

    name  age         city
0   John   28     New York
1  Alice   24  Los Angeles
2    Bob   35      Chicago

#### 4) creating dataframe using list dictionary sets or tuples

In [11]:
l=[12,23,34,345]
dataFrame=pd.DataFrame(l)
dataFrame

345

In [5]:
import pandas as pd
l=[12,23,34,345]
dataFrame=pd.DataFrame(data=l,index=['A','B','C','D'],columns=['A'],copy=True)
copied=pd.DataFrame(dataFrame.values,index=['R1','R2','R3','R4'])
copied

      0
R1   12
R2   23
R3   34
R4  345

## USE OF PD.SERIES

In [7]:
list=[12,23,34,45,56]
l=pd.Series(list)
print(l)

0    12
1    23
2    34
3    45
4    56
dtype: int64

#### series using custom index

In [1]:
import pandas as pd
list=[12,23,34]
l=pd.Series(list,index=['a','b','c'])
print(l)

a    12
b    23
c    34
dtype: int64

## dataframe with dict

In [4]:
import pandas as pd
l={
    "name":["alice","John","Manish","Rohan","Manish","Aditya"],
    "Age":[12,23,34,23,32,15],
    "Course":["BCA","MCA","PGDCA","BCA","MCA","BCA"]
}
p=pd.DataFrame(l)
p

     name  Age Course
0   alice   12    BCA
1    John   23    MCA
2  Manish   34  PGDCA
3   Rohan   23    BCA
4  Manish   32    MCA
5  Aditya   15    BCA

## .head(n)   .tail(n)

In [6]:
print(p.head(2))
print(p.tail(3))

    name  Age Course
0  alice   12    BCA
1   John   23    MCA
     name  Age Course
3   Rohan   23    BCA
4  Manish   32    MCA
5  Aditya   15    BCA

### •	.info() - Print a concise summary of the DataFrame.

In [7]:
print(p.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   Age     6 non-null      int64
 2   Course  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes
None


### .shape - Get the number of rows and columns.

In [9]:
rows,cols=p.shape
print(rows,",",cols)

6 , 3

### .columns

In [10]:
print(p.columns)

Index(['name', 'Age', 'Course'], dtype='object')

### .describe()

In [13]:
print(p.describe())

             Age
count   6.000000
mean   23.166667
std     8.795832
min    12.000000
25%    17.000000
50%    23.000000
75%    29.750000
max    34.000000

In [15]:
print(p.describe(include='all'))

          name        Age Course
count        6   6.000000      6
unique       5        NaN      3
top     Manish        NaN    BCA
freq         2        NaN      3
mean       NaN  23.166667    NaN
std        NaN   8.795832    NaN
min        NaN  12.000000    NaN
25%        NaN  17.000000    NaN
50%        NaN  23.000000    NaN
75%        NaN  29.750000    NaN
max        NaN  34.000000    NaN

### dtypes

In [19]:
print(p.dtypes)

name      object
Age        int64
Course    object
dtype: object

## .value_counts()

In [23]:
print(p.value_counts())

name    Age  Course
Aditya  15   BCA       1
John    23   MCA       1
Manish  32   MCA       1
        34   PGDCA     1
Rohan   23   BCA       1
alice   12   BCA       1
Name: count, dtype: int64

# ADDING NEW COLUMNS IN TABLE

In [2]:
import pandas as pd
l={
    "name":["alice","John","Manish","Rohan","Manish","Aditya"],
    "Age":[12,23,34,23,32,15],
    "Course":["BCA","MCA","PGDCA","BCA","MCA","BCA"]
}
p=pd.DataFrame(l)
p["Salary"]=[20000,30000,40000,12000,23000,90000]
print(p)

     name  Age Course  Salary
0   alice   12    BCA   20000
1    John   23    MCA   30000
2  Manish   34  PGDCA   40000
3   Rohan   23    BCA   12000
4  Manish   32    MCA   23000
5  Aditya   15    BCA   90000

# adding calculated value in new column

In [4]:
p["Bouns"]=p["Salary"] * 0.1
print(p)

     name  Age Course  Salary   Bouns
0   alice   12    BCA   20000  2000.0
1    John   23    MCA   30000  3000.0
2  Manish   34  PGDCA   40000  4000.0
3   Rohan   23    BCA   12000  1200.0
4  Manish   32    MCA   23000  2300.0
5  Aditya   15    BCA   90000  9000.0

# ADDING NEW COLUMN USING INSERT METHOD

In [10]:

print(p)

        EMPLOYEEID    name  Age Course  Salary   Bouns
0  EDUrange(10, 6)   alice   12    BCA   20000  2000.0
1  EDUrange(10, 6)    John   23    MCA   30000  3000.0
2  EDUrange(10, 6)  Manish   34  PGDCA   40000  4000.0
3  EDUrange(10, 6)   Rohan   23    BCA   12000  1200.0
4  EDUrange(10, 6)  Manish   32    MCA   23000  2300.0
5  EDUrange(10, 6)  Aditya   15    BCA   90000  9000.0

# UPDATING ANY SPECIFIC VALUE

In [11]:
p.loc[0,"name"]="ALICE"
print(p)

        EMPLOYEEID    name  Age Course  Salary   Bouns
0  EDUrange(10, 6)   ALICE   12    BCA   20000  2000.0
1  EDUrange(10, 6)    John   23    MCA   30000  3000.0
2  EDUrange(10, 6)  Manish   34  PGDCA   40000  4000.0
3  EDUrange(10, 6)   Rohan   23    BCA   12000  1200.0
4  EDUrange(10, 6)  Manish   32    MCA   23000  2300.0
5  EDUrange(10, 6)  Aditya   15    BCA   90000  9000.0

# UPDATING MULTIPLE VALUES AT ONCE

In [16]:
p["EMPLOYEEID"]=[101,102,103,104,105,106]
print(p)

   EMPLOYEEID    name  Age Course  Salary
0         101   ALICE   12    BCA   20000
1         102    John   23    MCA   30000
2         103  Manish   34  PGDCA   40000
3         104   Rohan   23    BCA   12000
4         105  Manish   32    MCA   23000
5         106  Aditya   15    BCA   90000

# REMOVING ANY COLUMN

In [15]:
p.drop(columns=["Bouns"],inplace=True)
print(p)

   EMPLOYEEID    name  Age Course  Salary
0         101   ALICE   12    BCA   20000
1         102    John   23    MCA   30000
2         103  Manish   34  PGDCA   40000
3         104   Rohan   23    BCA   12000
4         105  Manish   32    MCA   23000
5         106  Aditya   15    BCA   90000

# FINDING MISSING VALUES

In [21]:
import pandas as pd
l={
    "name":["alice",None,"Manish","Rohan","Manish","Aditya"],
    "Age":[12,None,34,23,32,15],
    "Course":["BCA",None,"PGDCA","BCA","MCA","BCA"]
}
ps=pd.DataFrame(l)
print(ps.isnull())
print("Total missing values: ",ps.isnull().sum())

    name    Age  Course
0  False  False   False
1   True   True    True
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
Total missing values:  name      1
Age       1
Course    1
dtype: int64

# REMOVING ANY MISSING VALUE in ROWS

In [24]:
ps.dropna(axis=0,inplace=True)
ps["none"]=[None,None,None,None,None]
print(ps)

     name   Age Course  none
0   alice  12.0    BCA  None
2  Manish  34.0  PGDCA  None
3   Rohan  23.0    BCA  None
4  Manish  32.0    MCA  None
5  Aditya  15.0    BCA  None

# REMOVING MISSING VALUES IN COLUMNS

In [25]:
ps.dropna(axis=1,inplace=True)
print(ps)

     name   Age Course
0   alice  12.0    BCA
2  Manish  34.0  PGDCA
3   Rohan  23.0    BCA
4  Manish  32.0    MCA
5  Aditya  15.0    BCA

# REMOVING ALL THE MISSING VALUES

In [26]:
import pandas as pd
l={
    "name":["alice",None,"Manish","Rohan",None,"Aditya"],
    "Age":[12,None,34,23,32,15],
    "Course":["BCA",None,"PGDCA","BCA","MCA","BCA"]
}
pr=pd.DataFrame(l)
print(pr)
print("Total missing values: ",pr.isnull().sum())

     name   Age Course
0   alice  12.0    BCA
1    None   NaN   None
2  Manish  34.0  PGDCA
3   Rohan  23.0    BCA
4    None  32.0    MCA
5  Aditya  15.0    BCA
Total missing values:  name      2
Age       1
Course    1
dtype: int64

In [27]:
pr.dropna(inplace=True)
print(pr)

     name   Age Course
0   alice  12.0    BCA
2  Manish  34.0  PGDCA
3   Rohan  23.0    BCA
5  Aditya  15.0    BCA

# FILLING VALUES IN PLACE OF MISSING VALUES

In [30]:
import pandas as pd
l={
    "name":["alice",None,"Manish","Rohan",None,"Aditya"],
    "Age":[12,None,34,23,32,15],
    "Course":["BCA",None,"PGDCA","BCA","MCA","BCA"]
}
pp=pd.DataFrame(l)
print(pp)

     name   Age Course
0   alice  12.0    BCA
1    None   NaN   None
2  Manish  34.0  PGDCA
3   Rohan  23.0    BCA
4    None  32.0    MCA
5  Aditya  15.0    BCA

In [33]:
pp["Age"].fillna(pp["Age"].mean(),inplace=True)
print(pp)

     name   Age Course
0   alice  12.0    BCA
1    None  23.2   None
2  Manish  34.0  PGDCA
3   Rohan  23.0    BCA
4    None  32.0    MCA
5  Aditya  15.0    BCA

# USING INTERPOLATION

In [38]:
new={
    "name":["name1","name2","name3","name4","name5"],
    "AGE":[12,23,None,45,56],
    "SALARY":[10000,None,23000,34000,1234]
}
pdf=pd.DataFrame(new)

pdf["AGE"]=pdf["AGE"].interpolate(method="linear")

print(pdf)

    name   AGE   SALARY
0  name1  12.0  10000.0
1  name2  23.0      NaN
2  name3  34.0  23000.0
3  name4  45.0  34000.0
4  name5  56.0   1234.0

# USING POLYNOMIAL INTERPOLATION

In [42]:
pdf["SALARY"]=pdf["SALARY"].interpolate(method="linear")
print(pdf)

    name   AGE   SALARY
0  name1  12.0  10000.0
1  name2  23.0  16500.0
2  name3  34.0  23000.0
3  name4  45.0  34000.0
4  name5  56.0   1234.0

# sorting and aggregation

In [49]:
employee = {
    "name": ["Manish Goswami","Alice Wonderland", "Bob the Builder", "Charlie Brown", "David Copperfield", "Emily Dickinson"],
    "id": ["EMP1000","EMP1001", "EMP1002", "EMP1003", "EMP1004", "EMP1005"],
    "salary": [23000,75000, 62000, 80000, 58000, 70000],
    "department": ["FINANCE","Marketing", "IT", "Finance", "HR", "Sales"]
}
pd2=pd.DataFrame(employee)
pd2.sort_values(by="department",inplace=True)
print(pd2)

                name       id  salary department
0     Manish Goswami  EMP1000   23000    FINANCE
3      Charlie Brown  EMP1003   80000    Finance
4  David Copperfield  EMP1004   58000         HR
2    Bob the Builder  EMP1002   62000         IT
1   Alice Wonderland  EMP1001   75000  Marketing
5    Emily Dickinson  EMP1005   70000      Sales

# GROUPING DATA

In [50]:
grouped=pd2.groupby("department")["salary"].sum()
print(grouped)

department
FINANCE      23000
Finance      80000
HR           58000
IT           62000
Marketing    75000
Sales        70000
Name: salary, dtype: int64

In [52]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emily", "Frank", "Grace", "Henry", "Isaac", "Jane"],
    "Age": [25, 30, 22, 28, 35, 27, 24, 32, 29, 26],
    "City": ["New York", "London", "Paris", "New York", "London", "Paris", "New York", "London", "Paris", "New York"],
    "Department": ["Sales", "Marketing", "IT", "Sales", "Marketing", "IT", "Sales", "Marketing", "IT", "Sales"]
}
dataframe=pd.DataFrame(data)
print(dataframe)

      Name  Age      City Department
0    Alice   25  New York      Sales
1      Bob   30    London  Marketing
2  Charlie   22     Paris         IT
3    David   28  New York      Sales
4    Emily   35    London  Marketing
5    Frank   27     Paris         IT
6    Grace   24  New York      Sales
7    Henry   32    London  Marketing
8    Isaac   29     Paris         IT
9     Jane   26  New York      Sales

### GROUPING data on the basis of department

In [55]:
grouped=dataframe.groupby(["Department","Age"])["Name"].count()
print(grouped)

Department  Age
IT          22     1
            27     1
            29     1
Marketing   30     1
            32     1
            35     1
Sales       24     1
            25     1
            26     1
            28     1
Name: Name, dtype: int64

# MERGING AND JOINING

In [60]:
import pandas as pd

# Dataset 1: Customer Information
customer_df = pd.DataFrame({
    'Customer_ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
    'City': ['New York', 'London', 'Paris', 'New York', 'London']
})

# Dataset 2: Order Information
order_df = pd.DataFrame({
    'Order_ID': [101, 102, 103, 104, 105],
    'Customer_ID': [1, 2, 1, 3, 5],
    'Order_Date': ['2023-01-15', '2023-02-20', '2023-03-10', '2023-04-05', '2023-05-12']
})

# Dataset 3: Product Information
product_df = pd.DataFrame({
    'Product_ID': [1, 2, 3],
    'Product_Name': ['Laptop', 'Phone', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics']
})
print(customer_df,end="\n\n\n\n")
print(order_df)

   Customer_ID     Name      City
0            1    Alice  New York
1            2      Bob    London
2            3  Charlie     Paris
3            4    David  New York
4            5    Emily    London



   Order_ID  Customer_ID  Order_Date
0       101            1  2023-01-15
1       102            2  2023-02-20
2       103            1  2023-03-10
3       104            3  2023-04-05
4       105            5  2023-05-12

## INNSER JOIN

In [57]:
mergedInner=pd.merge(customer_df,order_df, on="Customer_ID", how="inner")
print(mergedInner)

   Customer_ID     Name      City  Order_ID  Order_Date
0            1    Alice  New York       101  2023-01-15
1            1    Alice  New York       103  2023-03-10
2            2      Bob    London       102  2023-02-20
3            3  Charlie     Paris       104  2023-04-05
4            5    Emily    London       105  2023-05-12

### OUTER

In [61]:
mergedInner=pd.merge(customer_df,order_df, on="Customer_ID", how="outer")
print(mergedInner)

   Customer_ID     Name      City  Order_ID  Order_Date
0            1    Alice  New York     101.0  2023-01-15
1            1    Alice  New York     103.0  2023-03-10
2            2      Bob    London     102.0  2023-02-20
3            3  Charlie     Paris     104.0  2023-04-05
4            4    David  New York       NaN         NaN
5            5    Emily    London     105.0  2023-05-12

### LEFT

In [62]:
mergedInner=pd.merge(customer_df,order_df, on="Customer_ID", how="left")
print(mergedInner)

   Customer_ID     Name      City  Order_ID  Order_Date
0            1    Alice  New York     101.0  2023-01-15
1            1    Alice  New York     103.0  2023-03-10
2            2      Bob    London     102.0  2023-02-20
3            3  Charlie     Paris     104.0  2023-04-05
4            4    David  New York       NaN         NaN
5            5    Emily    London     105.0  2023-05-12

### RIGHT

In [63]:
mergedInner=pd.merge(customer_df,order_df, on="Customer_ID", how="right")
print(mergedInner)

   Customer_ID     Name      City  Order_ID  Order_Date
0            1    Alice  New York       101  2023-01-15
1            2      Bob    London       102  2023-02-20
2            1    Alice  New York       103  2023-03-10
3            3  Charlie     Paris       104  2023-04-05
4            5    Emily    London       105  2023-05-12

# MERGING DATA SETS

In [65]:
import pandas as pd

# Dataset 1: Students
students_df = pd.DataFrame({
    'Student_ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Grade': ['A', 'B', 'A']
})

# Dataset 2: Courses
courses_df = pd.DataFrame({
    'Course_ID': [101, 102, 103],
    'Course_Name': ['Math', 'Science', 'English']
})

# Dataset 3: Student_Courses (Linking Students and Courses)
student_courses_df = pd.DataFrame({
    'Student_ID': [1, 1, 2, 3],
    'Course_ID': [101, 102, 101, 103]
})

print(students_df,end="\n\n\n\n\n")
print(student_courses_df,end="\n\n\n\n\n")
print(courses_df,end="\n\n\n\n\n")

   Student_ID     Name Grade
0           1    Alice     A
1           2      Bob     B
2           3  Charlie     A




   Student_ID  Course_ID
0           1        101
1           1        102
2           2        101
3           3        103




   Course_ID Course_Name
0        101        Math
1        102     Science
2        103     English

In [70]:
concate=pd.concat([students_df,student_courses_df,courses_df],axis=1,ignore_index=True)
print(concate)

     0        1    2  3    4      5        6
0  1.0    Alice    A  1  101  101.0     Math
1  2.0      Bob    B  1  102  102.0  Science
2  3.0  Charlie    A  2  101  103.0  English
3  NaN      NaN  NaN  3  103    NaN      NaN